### ISSUE TITLE
Text hard to read in certain places

### ISSUE THREAD

**Issue by fosspill** [EliverLara/Ant#78] opened 2019-08-01 12:07 UTC
Hi!
I absolutely love the Ant themes, but I'm having a hard time figuring out why the text is hard to read in some places.

Gnome 3.32.2.

Evolution calendar-acceptance buttons are impossible to read:
![Screenshot from 2019-08-01 14-04-32](https://user-images.githubusercontent.com/1491401/62291887-53139680-b465-11e9-8346-4b6340cc0d45.png)

The main gnome searchbar is really hard to read:
![Screenshot from 2019-08-01 14-05-19](https://user-images.githubusercontent.com/1491401/62291934-76d6dc80-b465-11e9-9eb1-521794307648.png)

Some other texts, such as with the emoji picker extension is almost impossible to read:
![Screenshot from 2019-08-01 14-07-10](https://user-images.githubusercontent.com/1491401/62292024-adacf280-b465-11e9-866a-d432409fc7e5.png)

Would it be possible to get this corrected, or could I be pointed to the right place to fix it? :)

**Comment by EliverLara** [comment] 2019-08-01 17:51
Hi, thanks for reporting! I'm working on it

**Comment by EliverLara** [comment] 2019-08-01 20:11
I have already fixed the evolution issue, but now I am not able to reproduce the issue with gnome-shell (as you can see it looks good in my session),

![Captura de pantalla de 2019-08-01 14-26-34](https://user-images.githubusercontent.com/9838260/62323818-bef9fd00-b46d-11e9-9fee-fff54955a95a.png)
![Captura de pantalla de 2019-08-01 14-24-58](https://user-images.githubusercontent.com/9838260/62323819-bf929380-b46d-11e9-91cb-640e54184fc3.png)

 I have made some adjustments where I think the issue could be, so Could you help me test if it worked? just replacing the current gnome-shell.css file with [this one](https://github.com/EliverLara/Ant/files/3458484/gnome-shell.zip)

**Comment by fosspill** [comment] 2019-08-01 21:03
That's very interesting. Might somehow be Pop OS specific then.

I'll try it when I'm back in front of my work laptop tomorrow morning :D

**Comment by fosspill** [comment] 2019-08-02 10:44
@EliverLara Good and bad news!
The good news is that the .css file you provided fixes the gnome search box BEFORE I type in it.

The bad news is that the text is still white after I start typing.

![gnomeshellcss gif](https://user-images.githubusercontent.com/1491401/62364994-35a50200-b523-11e9-8f03-edf1f78598c6.gif)

**Comment by EliverLara** [comment] 2019-08-18 18:01
That should be fixed now

**Comment by fosspill** [comment] 2019-08-18 21:31
Awesome, thank you!
I'll give it a go soon and close the issue

**Closed** 2019-08-19 08:07 UTC

**Comment by risoul** [comment] 2021-08-07 10:55
Old issue, but on a fresh ubuntu budgie install, I always have white text on grey in budgie menu. Could you tell me what class to change?

![image](https://user-images.githubusercontent.com/10132802/128597838-a143cc49-9abd-4e03-a5f4-877a2b7ba2a5.png)
